name: Build EXE

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # choose your Python version

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Print current directory
      run: |
        python -c "import os; print('Current working directory:', os.getcwd())"
        python -c "import os; print('Contents of the directory:', os.listdir())"

    - name: Run Python script
      run: python App.py

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile App.py --add-data "./sivan22/orach-chaim;./sivan22/orach-chaim" --add-data "./sivan22/halacha-siman-seif-classifier-new;./sivan22/halacha-siman-seif-classifier-new"

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: app-exe
        path: dist\App.exe  # Adjust the path to the EXE file
